version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:9.1.7 # (Phiên bản này ổn định)
    container_name: es01
    environment:
      - discovery.type=single-node
      # TẮT BẢO MẬT (Chỉ dùng cho local dev)
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data

volumes:
  esdata01: